// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cisoapedlquauvppqvhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpc29hcGVkbHF1YXV2cHBxdmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMzEzMjEsImV4cCI6MjA3MDcwNzMyMX0.FPG8UdsGc-Hk01pmPhhcVWIarui6r2NbsJfC0mdpXqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});